export const skills = [
  ["devicon-html5-plain colored", "HTML"],
  ["devicon-css3-plain colored", "CSS"],
  ["devicon-javascript-plain colored", "JavaScript"],
  ["sql", "SQL"],
  ["devicon-firebase-plain colored", "Firebase"],
  ["devicon-python-plain colored", "Python"],
  ["devicon-react-original colored", "React"],
  ["devicon-nodejs-plain colored", "Node.js"],
  ["devicon-typescript-plain colored", "TypeScript"],
  ["devicon-figma-plain colored", "Figma"],
];

export const worldProjects = [
  {
    slug: "azukeria",
    title: "AZUKERIA",
    cover: "/projeto/azukeria-1.webp",
    images: ["/projeto/azukeria-1.webp", "/projeto/azukeria-3.webp", "/projeto/azukeria-2.webp"],
    width: 1600,
    height: 756,
    alt: "Página inicial da AZUKERIA",
    descriptionKey: "azukeriaProjectDescription",
    typeKey: "azukeriaProjectType",
    countryKey: "azukeriaProjectCountry",
    linkKey: "azukeriaProjectLink",
    featured: true,
  },
  {
    slug: "parka",
    title: "PARKA Bakehouse",
    cover: "/projeto/parka-2.webp",
    images: ["/projeto/parka-2.webp", "/projeto/parka-1.webp", "/projeto/parka-3.webp"],
    width: 1600,
    height: 737,
    alt: "Página inicial da PARKA Bakehouse",
    descriptionKey: "parkaProjectDescription",
    typeKey: "parkaProjectType",
    countryKey: "parkaProjectCountry",
    linkKey: "parkaProjectLink",
  },
  {
    slug: "hidden-brew",
    title: "The Hidden Brew",
    cover: "/projeto/hidden-brew-1.webp",
    images: ["/projeto/hidden-brew-1.webp", "/projeto/hidden-brew-3.webp", "/projeto/hidden-brew-2.webp"],
    width: 1600,
    height: 767,
    alt: "Página inicial do The Hidden Brew",
    number: "2026",
    descriptionKey: "hiddenBrewProjectDescription",
    typeKey: "hiddenBrewProjectType",
    countryKey: "hiddenBrewProjectCountry",
    linkKey: "hiddenBrewProjectLink",
  },
  {
    slug: "cares",
    title: "CARÉS COFFEE CLUB",
    cover: "/projeto/cares-coffee-1-v2.webp",
    images: ["/projeto/cares-coffee-1-v2.webp", "/projeto/cares-coffee-2-v2.webp", "/projeto/cares-coffee-3-v2.webp"],
    width: 1600,
    height: 758,
    alt: "Página inicial do Carés Coffee Club",
    descriptionKey: "realProjectDescription",
    typeKey: "realProjectType",
    countryKey: "realProjectCountry",
    linkKey: "realProjectLink",
  },
  {
    slug: "terrio",
    title: "TERRIO CAFÉ LONDRINA",
    cover: "/projeto/terrio-cafe-1.webp",
    images: ["/projeto/terrio-cafe-1.webp", "/projeto/terrio-cafe-2.webp", "/projeto/terrio-cafe-3.webp"],
    width: 1600,
    height: 764,
    alt: "Página inicial do Terrio Café Londrina",
    descriptionKey: "terrioProjectDescription",
    typeKey: "terrioProjectType",
    countryKey: "terrioProjectCountry",
    linkKey: "terrioProjectLink",
  },
  {
    slug: "banana",
    title: "BANANA COFFEE",
    cover: "/projeto/banana-coffee-1-v2.webp",
    images: ["/projeto/banana-coffee-1-v2.webp", "/projeto/banana-coffee-2.webp", "/projeto/banana-coffee-3.webp"],
    width: 1600,
    height: 772,
    alt: "Página inicial da Banana Coffee",
    descriptionKey: "bananaProjectDescription",
    typeKey: "bananaProjectStatus",
    countryKey: "bananaProjectCountry",
    linkKey: "bananaProjectLink",
  },
  {
    slug: "draugu",
    title: "DRAUGU DESERTINÉ",
    cover: "/projeto/draugu-desertine-1.webp",
    images: ["/projeto/draugu-desertine-1.webp", "/projeto/draugu-desertine-2.webp", "/projeto/draugu-desertine-3.webp"],
    width: 1600,
    height: 781,
    alt: "Página inicial da Draugu Desertiné",
    descriptionKey: "drauguProjectDescription",
    typeKey: "drauguProjectType",
    countryKey: "drauguProjectCountry",
    linkKey: "drauguProjectLink",
  },
  {
    slug: "provence",
    title: "PROVENCE CAFÉS ESPECIAIS",
    cover: "/projeto/provence-cafes-1.webp",
    images: ["/projeto/provence-cafes-1.webp", "/projeto/provence-cafes-2-v2.webp", "/projeto/provence-cafes-3.webp"],
    width: 1600,
    height: 771,
    alt: "Página inicial da Provence Cafés Especiais",
    descriptionKey: "provenceProjectDescription",
    typeKey: "provenceProjectType",
    countryKey: "provenceProjectCountry",
    linkKey: "provenceProjectLink",
  },
  {
    slug: "molly",
    title: "MOLLY COFFEE",
    cover: "/projeto/molly-coffee-1.webp",
    images: ["/projeto/molly-coffee-1.webp", "/projeto/molly-coffee-2.webp", "/projeto/molly-coffee-3.webp"],
    width: 1600,
    height: 768,
    alt: "Página inicial da Molly Coffee",
    descriptionKey: "mollyProjectDescription",
    typeKey: "mollyProjectType",
    countryKey: "mollyProjectCountry",
    linkKey: "mollyProjectLink",
  },
];

export const personalProjects = [
  {
    slug: "manager",
    title: "Kings League Manager",
    cover: "/projeto/kings-manager-1.webp",
    images: ["/projeto/kings-manager-1.webp", "/projeto/kings-manager-2.webp", "/projeto/kings-manager-3.webp"],
    width: 1600,
    height: 757,
    alt: "Tela do Kings League Manager",
    numberKey: "featured",
    statusKey: "development",
    tag: "Web",
  },
  {
    slug: "ea",
    title: "EA27 Club",
    cover: "/projeto/ea27-club-1.webp",
    images: ["/projeto/ea27-club-1.webp", "/projeto/ea27-club-2.webp", "/projeto/ea27-club-3.webp"],
    width: 1358,
    height: 926,
    alt: "Telas do EA27 Club em dispositivos móveis",
    number: "2025–2026 — 02",
    statusKey: "updating",
    tag: "Web",
    href: "https://fif4-league.web.app/",
  },
  {
    slug: "penalty",
    title: "KL PENALTY em C",
    cover: "/projeto/projeto3_1.webp",
    images: ["/projeto/projeto3_1.webp", "/projeto/projeto3_3.webp", "/projeto/projeto3_4.webp", "/projeto/projeto3_7.webp", "/projeto/projeto3_8.webp"],
    width: 1471,
    height: 752,
    alt: "Tela do KL PENALTY em C",
    number: "2025 — 03",
    status: "C",
    tag: "Game",
    href: "https://github.com/jrlescovar/kleaguepenalty_em_C",
  },
  {
    slug: "dbase",
    title: "dBase em C",
    cover: "/projeto/projeto4_1.webp",
    images: ["/projeto/projeto4_1.webp", "/projeto/projeto4_2.webp", "/projeto/projeto4_3.webp", "/projeto/projeto4_4.webp"],
    width: 1600,
    height: 912,
    alt: "Tela do dBase em C",
    number: "2025 — 04",
    status: "C",
    tag: "Database",
    href: "https://github.com/jrlescovar/dBase-w-linked-list",
  },
];

export const navigationTargets = ["sobre", "habilidades", "projetos", "contato"];
export const sidebarTargets = ["inicio", "sobre", "habilidades", "projetos", "contato"];
